import { useState, useMemo } from "react";
import { Link, useParams } from "wouter";
import PublicLayout from "@/components/PublicLayout";
import SEOMeta from "@/components/SEOMeta";
import Breadcrumb from "@/components/Breadcrumb";
import { Search, ChevronRight } from "lucide-react";

// ─── Glossary Data ─────────────────────────────────────────────────────────────

export const GLOSSARY_TERMS: {
  slug: string;
  term: string;
  category: string;
  shortDef: string;
  fullDef: string;
  example?: string;
  related?: string[];
}[] = [
  { slug: "apr", term: "APR (Annual Percentage Rate)", category: "Loans & Credit", shortDef: "The yearly cost of borrowing money, including interest and fees.", fullDef: "APR stands for Annual Percentage Rate. It represents the true annual cost of borrowing, expressed as a percentage. Unlike a simple interest rate, APR includes not just the interest charged but also any fees required to get the loan — such as origination fees, closing costs, or annual fees on credit cards. This makes APR a more accurate measure for comparing loan offers from different lenders.", example: "A mortgage advertised at 6.5% interest rate might have a 6.8% APR once origination fees are included. Always compare APRs — not just interest rates — when shopping for loans.", related: ["apy", "interest-rate", "origination-fee"] },
  { slug: "apy", term: "APY (Annual Percentage Yield)", category: "Savings & Investing", shortDef: "The real rate of return on savings, accounting for compound interest.", fullDef: "APY stands for Annual Percentage Yield. It reflects the actual amount of interest you earn on a savings account or investment over one year, taking into account the effect of compounding. Because interest compounds (earns interest on itself), APY is always higher than the stated interest rate. APY is the standard metric used to compare savings accounts, CDs, and money market accounts.", example: "A savings account with a 5.0% interest rate compounded monthly has an APY of approximately 5.12%. The difference grows larger with higher rates and more frequent compounding.", related: ["apr", "compound-interest", "cd"] },
  { slug: "amortization", term: "Amortization", category: "Loans & Credit", shortDef: "The process of paying off a loan through regular scheduled payments over time.", fullDef: "Amortization is the process of gradually paying off a debt through a series of fixed, regular payments. Each payment covers both interest and a portion of the principal. In the early years of a loan, most of each payment goes toward interest. Over time, as the principal decreases, a larger portion of each payment reduces the balance. A fully amortized loan is paid off completely by the end of its term.", example: "On a 30-year $300,000 mortgage at 7%, your first payment of ~$1,996 might include $1,750 in interest and only $246 toward principal. By year 25, the split reverses.", related: ["principal", "interest-rate", "loan-term"] },
  { slug: "balance-transfer", term: "Balance Transfer", category: "Credit Cards", shortDef: "Moving debt from one credit card to another, usually to get a lower interest rate.", fullDef: "A balance transfer is when you move existing credit card debt from one card to another — typically to take advantage of a lower interest rate or a promotional 0% APR offer. Many cards offer 0% APR on balance transfers for 12–21 months, which can save significant interest if you pay off the balance before the promotional period ends. Most cards charge a balance transfer fee of 3–5% of the amount transferred.", example: "If you have $5,000 on a card at 24% APR, transferring it to a card with 0% APR for 18 months could save you over $1,000 in interest — minus a ~$150 transfer fee.", related: ["apr", "credit-utilization", "introductory-rate"] },
  { slug: "bankruptcy", term: "Bankruptcy", category: "Debt & Credit", shortDef: "A legal process that allows individuals or businesses to discharge or restructure debts they cannot repay.", fullDef: "Bankruptcy is a federal legal process that provides relief to individuals and businesses who cannot repay their debts. For consumers, Chapter 7 bankruptcy eliminates most unsecured debts (like credit cards) but requires liquidating non-exempt assets. Chapter 13 allows you to keep assets while repaying debts through a 3–5 year court-approved plan. Bankruptcy severely damages your credit score and remains on your credit report for 7–10 years.", example: "After filing Chapter 7 bankruptcy, most unsecured debts are discharged within 3–6 months, but the bankruptcy stays on your credit report for 10 years, making new credit difficult and expensive.", related: ["credit-score", "debt-consolidation", "charge-off"] },
  { slug: "cash-back", term: "Cash Back", category: "Credit Cards", shortDef: "A credit card reward that returns a percentage of your spending as cash.", fullDef: "Cash back is a type of credit card reward where you earn a percentage of your purchases returned to you as cash, statement credits, or deposits. Cards typically offer flat-rate cash back (e.g., 2% on everything) or tiered rates (e.g., 5% on groceries, 3% on gas, 1% on everything else). Cash back is generally considered the simplest and most flexible reward type because it has no redemption restrictions.", example: "If you spend $2,000/month on a 2% flat-rate cash back card, you earn $480 per year in rewards — with no points to manage or blackout dates to worry about.", related: ["rewards-points", "apr", "annual-fee"] },
  { slug: "cd", term: "CD (Certificate of Deposit)", category: "Savings & Investing", shortDef: "A savings account that holds a fixed amount of money for a fixed period at a guaranteed interest rate.", fullDef: "A Certificate of Deposit (CD) is a type of savings account offered by banks and credit unions that pays a fixed interest rate in exchange for keeping your money deposited for a set period — typically ranging from 3 months to 5 years. CDs generally offer higher interest rates than regular savings accounts because you agree not to withdraw the funds early. Withdrawing before the maturity date typically incurs an early withdrawal penalty.", example: "A 12-month CD at 5.0% APY on a $10,000 deposit earns $500 in interest. If you withdraw after 6 months, you might forfeit 3 months of interest as a penalty.", related: ["apy", "fdic-insurance", "money-market"] },
  { slug: "charge-off", term: "Charge-Off", category: "Debt & Credit", shortDef: "When a lender writes off a debt as a loss after you've stopped making payments, usually after 180 days.", fullDef: "A charge-off occurs when a creditor determines that a debt is unlikely to be collected and removes it from their books as a loss — typically after 120–180 days of non-payment. Despite the name, a charge-off does not mean the debt is forgiven. You still legally owe the money, and the creditor can still attempt to collect it or sell it to a debt collection agency. A charge-off is one of the most damaging items that can appear on your credit report.", example: "If you stop paying a $3,000 credit card balance, after 6 months the bank may charge it off. The debt may then be sold to a collections agency that will attempt to collect the full amount.", related: ["collections", "credit-score", "debt-settlement"] },
  { slug: "closing-costs", term: "Closing Costs", category: "Mortgages", shortDef: "Fees and expenses paid at the closing of a real estate transaction, typically 2–5% of the loan amount.", fullDef: "Closing costs are the fees and expenses you pay when finalizing a mortgage or real estate transaction. They typically include lender fees (origination, underwriting), third-party fees (appraisal, title insurance, attorney), and prepaid items (homeowners insurance, property taxes, prepaid interest). Closing costs typically range from 2–5% of the loan amount and must be paid at closing unless rolled into the loan.", example: "On a $350,000 home purchase, closing costs of 3% would be $10,500. Some lenders offer 'no-closing-cost' mortgages that roll these fees into a higher interest rate.", related: ["origination-fee", "apr", "escrow"] },
  { slug: "co-signer", term: "Co-Signer", category: "Loans & Credit", shortDef: "A person who agrees to be equally responsible for repaying a loan if the primary borrower cannot.", fullDef: "A co-signer is someone who agrees to share legal responsibility for a loan alongside the primary borrower. Lenders use the co-signer's credit history and income to help qualify the borrower for a loan or secure better terms. If the primary borrower fails to make payments, the co-signer is fully responsible for the debt. Co-signing can help someone with limited or poor credit access financing, but it carries significant risk for the co-signer.", example: "A college student with no credit history might need a parent to co-sign a private student loan. If the student misses payments, it damages the parent's credit score as well.", related: ["credit-score", "debt-to-income-ratio", "guarantor"] },
  { slug: "collections", term: "Collections", category: "Debt & Credit", shortDef: "When an unpaid debt is transferred to a collection agency that attempts to recover the money.", fullDef: "When a debt goes unpaid for an extended period, the original creditor may sell it to or hire a third-party debt collection agency. The collection agency then attempts to recover the debt by contacting you directly. A collection account on your credit report is a serious negative mark that can lower your score significantly. Under the Fair Debt Collection Practices Act (FDCPA), collectors must follow strict rules about how and when they can contact you.", example: "A $500 medical bill unpaid for 6 months may be sold to a collections agency for $100. The agency then pursues you for the full $500. The collection appears on your credit report for 7 years.", related: ["charge-off", "credit-score", "debt-settlement"] },
  { slug: "compound-interest", term: "Compound Interest", category: "Savings & Investing", shortDef: "Interest calculated on both the initial principal and the accumulated interest from previous periods.", fullDef: "Compound interest is interest that is calculated not just on the original principal but also on the interest that has already been earned or charged. This creates a snowball effect — your money grows faster over time because each period's interest becomes part of the new principal. Compound interest works in your favor when saving (your savings grow faster) and against you when borrowing (your debt grows faster if not paid down).", example: "$10,000 invested at 7% simple interest earns $700/year. At 7% compound interest (annually), after 10 years you'd have $19,672 — nearly $700 more than simple interest would produce.", related: ["apy", "interest-rate", "cd"] },
  { slug: "credit-bureau", term: "Credit Bureau", category: "Credit Score", shortDef: "A company that collects and maintains consumer credit information and produces credit reports.", fullDef: "A credit bureau (also called a credit reporting agency) is a company that collects financial data about consumers from lenders, creditors, and public records, and compiles it into credit reports. The three major credit bureaus in the United States are Equifax, Experian, and TransUnion. Lenders use your credit report to evaluate your creditworthiness when you apply for loans, credit cards, or other financial products. You are entitled to one free credit report from each bureau annually at AnnualCreditReport.com.", example: "When you apply for a mortgage, the lender typically pulls your credit report from all three bureaus and uses the middle score to make their decision.", related: ["credit-report", "credit-score", "hard-inquiry"] },
  { slug: "credit-limit", term: "Credit Limit", category: "Credit Cards", shortDef: "The maximum amount you're allowed to borrow on a credit card or line of credit.", fullDef: "A credit limit is the maximum balance you're allowed to carry on a revolving credit account, such as a credit card or home equity line of credit (HELOC). Your credit limit is set by the lender based on your credit score, income, and existing debt. Exceeding your credit limit can result in fees and may hurt your credit score. Keeping your balance well below your limit (ideally under 30%) is important for maintaining a good credit score.", example: "If your credit card has a $5,000 limit and you carry a $1,500 balance, your credit utilization is 30% — the upper boundary of what's considered acceptable.", related: ["credit-utilization", "credit-score", "revolving-credit"] },
  { slug: "credit-report", term: "Credit Report", category: "Credit Score", shortDef: "A detailed record of your credit history, including accounts, payment history, and public records.", fullDef: "A credit report is a comprehensive record of your credit history compiled by a credit bureau. It includes personal identifying information, a list of all your credit accounts (open and closed), payment history, credit inquiries, and public records such as bankruptcies or judgments. Lenders, landlords, and employers (with your permission) use your credit report to evaluate your financial reliability. You can get a free copy from each of the three major bureaus once per year at AnnualCreditReport.com.", example: "Your credit report might show 8 open accounts, 2 closed accounts, a mortgage, no missed payments in 5 years, and 2 hard inquiries from the past 12 months.", related: ["credit-bureau", "credit-score", "hard-inquiry"] },
  { slug: "credit-score", term: "Credit Score", category: "Credit Score", shortDef: "A three-digit number (300–850) that represents your creditworthiness based on your credit history.", fullDef: "A credit score is a numerical summary of your credit history, typically ranging from 300 to 850. The most widely used scoring model is the FICO score, though VantageScore is also common. Scores are calculated from five factors: payment history (35%), credit utilization (30%), length of credit history (15%), credit mix (10%), and new inquiries (10%). Higher scores indicate lower risk to lenders and typically result in better loan terms and lower interest rates.", example: "A borrower with a 760 credit score might qualify for a 6.5% mortgage rate, while someone with a 620 score might be offered 8.0% — a difference that adds up to tens of thousands of dollars over 30 years.", related: ["credit-report", "credit-bureau", "fico-score"] },
  { slug: "credit-utilization", term: "Credit Utilization", category: "Credit Score", shortDef: "The percentage of your available credit that you're currently using.", fullDef: "Credit utilization is the ratio of your current credit card balances to your total credit card limits, expressed as a percentage. It is one of the most important factors in your credit score, accounting for 30% of your FICO score. Lenders view high utilization as a sign of financial stress. Keeping your utilization below 30% is generally recommended, and below 10% is ideal for the highest scores. Utilization is calculated both per card and across all cards combined.", example: "If you have two cards — one with a $3,000 limit and $900 balance, and one with a $7,000 limit and $700 balance — your total utilization is $1,600 / $10,000 = 16%, which is excellent.", related: ["credit-limit", "credit-score", "revolving-credit"] },
  { slug: "debt-consolidation", term: "Debt Consolidation", category: "Debt & Credit", shortDef: "Combining multiple debts into a single loan, often at a lower interest rate.", fullDef: "Debt consolidation is the process of taking out a new loan to pay off multiple existing debts, leaving you with a single monthly payment — ideally at a lower interest rate. Common methods include personal loans, balance transfer credit cards, and home equity loans. Consolidation can simplify your finances and reduce the total interest you pay, but it only works if you address the spending habits that created the debt in the first place.", example: "If you have $15,000 spread across three credit cards at 22–26% APR, consolidating into a personal loan at 12% APR could save you thousands in interest and reduce your monthly payment.", related: ["balance-transfer", "personal-loan", "debt-to-income-ratio"] },
  { slug: "debt-to-income-ratio", term: "Debt-to-Income Ratio (DTI)", category: "Loans & Credit", shortDef: "The percentage of your gross monthly income that goes toward debt payments.", fullDef: "Your debt-to-income ratio (DTI) is calculated by dividing your total monthly debt payments by your gross monthly income. Lenders use DTI to assess your ability to manage monthly payments and repay debts. Most conventional mortgage lenders prefer a DTI below 43%, with the best rates typically going to borrowers below 36%. DTI is separate from your credit score — you can have a great score but still be denied if your DTI is too high.", example: "If your gross monthly income is $6,000 and your monthly debt payments total $1,800 (mortgage $1,200, car $350, student loan $250), your DTI is 30% — which is considered good.", related: ["credit-score", "mortgage", "personal-loan"] },
  { slug: "default", term: "Default", category: "Loans & Credit", shortDef: "Failure to repay a loan according to its terms, typically after a prolonged period of missed payments.", fullDef: "A loan default occurs when a borrower fails to meet the legal obligations of a loan agreement — most commonly by missing payments for an extended period. The specific definition of default varies by loan type: federal student loans default after 270 days of non-payment, while mortgages may enter default after just one missed payment. Defaulting on a loan can result in the debt being sent to collections, legal action, wage garnishment, and severe damage to your credit score.", example: "Defaulting on a federal student loan can result in the entire balance becoming immediately due, your wages being garnished, and your tax refund being seized — all without a court order.", related: ["charge-off", "collections", "foreclosure"] },
  { slug: "down-payment", term: "Down Payment", category: "Mortgages", shortDef: "An upfront cash payment made when purchasing a home or vehicle, reducing the amount you need to borrow.", fullDef: "A down payment is the initial cash payment you make when purchasing a home, car, or other large asset. It represents the portion of the purchase price you're paying out of pocket, with the remainder financed through a loan. For mortgages, a 20% down payment is traditionally recommended to avoid private mortgage insurance (PMI). Larger down payments reduce your loan amount, monthly payment, and total interest paid.", example: "On a $400,000 home, a 10% down payment ($40,000) means borrowing $360,000. A 20% down payment ($80,000) means borrowing $320,000 and avoiding PMI, saving ~$150/month.", related: ["pmi", "loan-to-value", "closing-costs"] },
  { slug: "equity", term: "Equity", category: "Mortgages", shortDef: "The portion of your home's value that you actually own, calculated as market value minus outstanding mortgage balance.", fullDef: "Home equity is the difference between your home's current market value and the amount you still owe on your mortgage. Equity builds over time as you make mortgage payments (reducing your principal balance) and as your home appreciates in value. Equity can be accessed through a home equity loan, home equity line of credit (HELOC), or cash-out refinance. It represents your financial stake in the property.", example: "If your home is worth $500,000 and you owe $320,000 on your mortgage, you have $180,000 in equity — or 36% equity. You could potentially borrow against this equity for renovations or other needs.", related: ["heloc", "loan-to-value", "refinance"] },
  { slug: "escrow", term: "Escrow", category: "Mortgages", shortDef: "A third-party account that holds funds for property taxes and insurance as part of your mortgage payment.", fullDef: "In mortgage lending, an escrow account is a separate account managed by your lender that holds a portion of your monthly mortgage payment to cover property taxes and homeowners insurance. When these bills come due, the lender pays them from the escrow account. Escrow accounts ensure these critical expenses are always paid and protect the lender's collateral. Most lenders require escrow accounts when the down payment is less than 20%.", example: "If your annual property taxes are $4,800 and homeowners insurance is $1,200, your lender will collect $500/month ($6,000/12) in escrow on top of your principal and interest payment.", related: ["closing-costs", "pmi", "mortgage"] },
  { slug: "fdic-insurance", term: "FDIC Insurance", category: "Savings & Investing", shortDef: "Federal government insurance that protects bank deposits up to $250,000 per depositor, per institution.", fullDef: "The Federal Deposit Insurance Corporation (FDIC) is a U.S. government agency that insures deposits at member banks. If an FDIC-insured bank fails, depositors are protected up to $250,000 per depositor, per institution, per account category. This means your checking, savings, CDs, and money market accounts at a bank are covered up to this limit. Credit unions have equivalent protection through the NCUA.", example: "If you have $200,000 in a savings account and $100,000 in a CD at the same bank, only $250,000 is insured. The remaining $50,000 would be at risk if the bank failed.", related: ["cd", "savings-account", "money-market"] },
  { slug: "fico-score", term: "FICO Score", category: "Credit Score", shortDef: "The most widely used credit scoring model, created by Fair Isaac Corporation, ranging from 300 to 850.", fullDef: "The FICO score is the credit scoring model used by approximately 90% of top lenders in the United States. Created by the Fair Isaac Corporation, it ranges from 300 to 850 and is calculated from five weighted factors: payment history (35%), amounts owed/utilization (30%), length of credit history (15%), credit mix (10%), and new credit inquiries (10%). There are multiple FICO score versions, and scores can vary slightly between the three credit bureaus.", example: "When you apply for a mortgage, lenders typically pull your FICO scores from all three bureaus (Equifax, Experian, TransUnion) and use the middle score for their decision.", related: ["credit-score", "vantagescore", "credit-bureau"] },
  { slug: "fixed-rate", term: "Fixed-Rate Loan", category: "Loans & Credit", shortDef: "A loan with an interest rate that stays the same for the entire repayment period.", fullDef: "A fixed-rate loan has an interest rate that does not change over the life of the loan. Your monthly payment remains constant from the first payment to the last, making budgeting predictable and straightforward. Fixed-rate mortgages are the most common type in the United States. While fixed rates are often slightly higher than initial adjustable rates, they protect borrowers from rate increases over time.", example: "A 30-year fixed mortgage at 7% will have the same interest rate and similar monthly payment in year 1 and year 30. An adjustable-rate mortgage might start at 5.5% but could rise to 9% after the initial fixed period.", related: ["adjustable-rate-mortgage", "interest-rate", "mortgage"] },
  { slug: "foreclosure", term: "Foreclosure", category: "Mortgages", shortDef: "The legal process by which a lender takes possession of a property when the borrower fails to make mortgage payments.", fullDef: "Foreclosure is the legal process through which a lender repossesses a home after the borrower defaults on their mortgage. The process typically begins after 3–6 months of missed payments and can take anywhere from a few months to several years depending on the state. Foreclosure severely damages your credit score (typically dropping it 100–150 points) and remains on your credit report for 7 years. Alternatives include loan modification, forbearance, short sale, or deed in lieu of foreclosure.", example: "After missing 4 mortgage payments, a lender may initiate foreclosure proceedings. The homeowner typically has a redemption period to catch up on payments before the home is sold at auction.", related: ["default", "mortgage", "equity"] },
  { slug: "grace-period", term: "Grace Period", category: "Credit Cards", shortDef: "The time between the end of a billing cycle and the payment due date, during which no interest is charged on new purchases.", fullDef: "A grace period is the window of time — typically 21–25 days — between the end of your credit card's billing cycle and your payment due date. If you pay your full statement balance by the due date, you are not charged any interest on purchases made during that billing cycle. If you carry a balance from month to month, you lose your grace period and interest begins accruing immediately on new purchases.", example: "If your billing cycle ends on the 15th and your payment is due on the 10th of the following month, you have a 25-day grace period. Pay in full by the 10th and you pay zero interest.", related: ["apr", "minimum-payment", "statement-balance"] },
  { slug: "hard-inquiry", term: "Hard Inquiry", category: "Credit Score", shortDef: "A credit check initiated when you apply for new credit, which temporarily lowers your credit score.", fullDef: "A hard inquiry (also called a hard pull) occurs when a lender or creditor checks your credit report as part of a lending decision — such as when you apply for a credit card, mortgage, or auto loan. Hard inquiries are recorded on your credit report and can lower your score by a few points. The impact is typically small and fades within a year, and the inquiry itself falls off your report after 2 years. Multiple inquiries for the same loan type within a 45-day window are treated as a single inquiry.", example: "Applying for 3 credit cards in one month results in 3 hard inquiries. Shopping for a mortgage with 5 lenders over 30 days counts as just 1 inquiry under rate-shopping rules.", related: ["soft-inquiry", "credit-score", "credit-report"] },
  { slug: "heloc", term: "HELOC (Home Equity Line of Credit)", category: "Mortgages", shortDef: "A revolving line of credit secured by your home equity, similar to a credit card.", fullDef: "A Home Equity Line of Credit (HELOC) is a revolving credit line secured by the equity in your home. Like a credit card, you can borrow up to a set limit, repay it, and borrow again during the draw period (typically 10 years). After the draw period ends, you enter a repayment period (typically 20 years) where you can no longer draw funds and must repay the balance. HELOCs typically have variable interest rates tied to the prime rate.", example: "With $100,000 in home equity, you might qualify for a $80,000 HELOC. You draw $30,000 for a kitchen renovation, repay $20,000, then draw $15,000 for another project — all within your credit limit.", related: ["equity", "home-equity-loan", "loan-to-value"] },
  { slug: "interest-rate", term: "Interest Rate", category: "Loans & Credit", shortDef: "The percentage of a loan amount charged by a lender for the use of money, expressed annually.", fullDef: "An interest rate is the cost of borrowing money, expressed as a percentage of the loan amount per year. It is the base rate charged by a lender before fees are factored in. Interest rates can be fixed (staying the same throughout the loan term) or variable (changing based on a benchmark rate like the prime rate or SOFR). The interest rate is different from APR — APR includes fees and provides a more complete picture of borrowing costs.", example: "A $10,000 personal loan at a 10% interest rate would accrue $1,000 in interest in the first year (before any principal payments). The actual APR would be higher if there's an origination fee.", related: ["apr", "fixed-rate", "variable-rate"] },
  { slug: "introductory-rate", term: "Introductory Rate (Intro APR)", category: "Credit Cards", shortDef: "A temporary, promotional interest rate offered by credit cards for a limited time, often 0%.", fullDef: "An introductory rate is a special, temporary interest rate offered by credit card issuers to attract new customers. The most common form is a 0% APR offer on purchases or balance transfers for a set period — typically 12 to 21 months. After the introductory period ends, the rate resets to the card's regular APR. It's critical to understand when the intro period ends and what the regular rate will be.", example: "A card offers 0% APR on balance transfers for 18 months with a 3% transfer fee. If you transfer $6,000, you pay $180 upfront but save ~$1,080 in interest versus keeping it on a 20% APR card.", related: ["apr", "balance-transfer", "grace-period"] },
  { slug: "loan-term", term: "Loan Term", category: "Loans & Credit", shortDef: "The length of time you have to repay a loan.", fullDef: "The loan term is the agreed-upon period over which you will repay a loan. Longer terms result in lower monthly payments but more total interest paid. Shorter terms mean higher monthly payments but less total interest. Common mortgage terms are 15 and 30 years. Auto loans typically range from 24 to 84 months. Personal loans usually range from 12 to 84 months.", example: "A $20,000 auto loan at 7% over 36 months costs $617/month and $2,212 in total interest. The same loan over 72 months costs $342/month but $4,624 in total interest — more than double.", related: ["amortization", "interest-rate", "monthly-payment"] },
  { slug: "loan-to-value", term: "Loan-to-Value Ratio (LTV)", category: "Mortgages", shortDef: "The ratio of your loan amount to the appraised value of the property, expressed as a percentage.", fullDef: "Loan-to-Value (LTV) ratio is calculated by dividing the loan amount by the property's appraised value. Lenders use LTV to assess risk — a higher LTV means the lender is financing more of the property's value, which increases their risk. Most conventional lenders require an LTV of 80% or below to avoid PMI. FHA loans allow LTVs up to 96.5% with mortgage insurance.", example: "Buying a $400,000 home with a $320,000 loan gives an LTV of 80% ($320,000 / $400,000). At this LTV, you avoid PMI. An LTV above 80% typically requires PMI.", related: ["pmi", "down-payment", "equity"] },
  { slug: "minimum-payment", term: "Minimum Payment", category: "Credit Cards", shortDef: "The smallest amount you must pay on a credit card each month to keep the account in good standing.", fullDef: "The minimum payment is the lowest amount you can pay on your credit card bill without incurring a late fee or penalty. It is typically calculated as either a flat dollar amount (e.g., $25) or a percentage of your balance (e.g., 1–2%), whichever is greater. Paying only the minimum is one of the most expensive financial habits — it maximizes the interest you pay and can keep you in debt for decades.", example: "A $5,000 balance at 20% APR with a 2% minimum payment would take over 30 years to pay off and cost nearly $8,000 in interest — if you only ever make the minimum payment.", related: ["apr", "grace-period", "credit-card"] },
  { slug: "money-market", term: "Money Market Account", category: "Savings & Investing", shortDef: "A type of savings account that typically offers higher interest rates and limited check-writing or debit card access.", fullDef: "A money market account (MMA) is a type of deposit account offered by banks and credit unions that typically pays higher interest rates than regular savings accounts. MMAs often come with check-writing privileges and a debit card, though federal regulations traditionally limited withdrawals to 6 per month (this limit was suspended in 2020 but many banks still enforce it). MMAs are FDIC-insured up to $250,000.", example: "A money market account paying 4.5% APY on a $20,000 balance earns $900 per year in interest — significantly more than a traditional savings account at 0.5% APY ($100/year).", related: ["apy", "fdic-insurance", "savings-account"] },
  { slug: "mortgage", term: "Mortgage", category: "Mortgages", shortDef: "A loan used to purchase real estate, secured by the property itself.", fullDef: "A mortgage is a type of loan specifically used to purchase real estate, where the property itself serves as collateral. If the borrower fails to make payments, the lender can foreclose on and sell the property to recover the debt. Mortgages typically have terms of 15 or 30 years and can have fixed or adjustable interest rates. The monthly payment usually includes principal, interest, property taxes, and homeowners insurance (PITI).", example: "A 30-year fixed mortgage for $350,000 at 7% APR results in a monthly principal and interest payment of approximately $2,329, for a total repayment of ~$838,000 over the life of the loan.", related: ["amortization", "pmi", "refinance"] },
  { slug: "origination-fee", term: "Origination Fee", category: "Loans & Credit", shortDef: "An upfront fee charged by a lender to process a new loan application.", fullDef: "An origination fee is a charge by a lender to cover the administrative costs of processing a loan application. It is typically expressed as a percentage of the loan amount (commonly 0.5–1% for mortgages, 1–8% for personal loans) and is either paid upfront at closing or rolled into the loan balance. Origination fees are included in the APR calculation, which is why APR is always higher than the stated interest rate.", example: "A personal loan of $10,000 with a 5% origination fee means $500 is deducted upfront — you receive $9,500 but repay the full $10,000 plus interest.", related: ["apr", "closing-costs", "points"] },
  { slug: "personal-loan", term: "Personal Loan", category: "Loans & Credit", shortDef: "An unsecured loan that can be used for almost any purpose, repaid in fixed monthly installments.", fullDef: "A personal loan is a type of installment loan that provides a lump sum of money you repay in fixed monthly payments over a set term (typically 2–7 years). Unlike mortgages or auto loans, personal loans are usually unsecured — meaning no collateral is required. They can be used for almost any purpose: debt consolidation, home improvement, medical expenses, or major purchases. Interest rates vary widely based on your credit score.", example: "A $15,000 personal loan at 11% APR over 48 months results in monthly payments of ~$388 and total interest of ~$3,624. The same loan at 22% APR would cost ~$462/month and ~$7,176 in total interest.", related: ["apr", "debt-consolidation", "unsecured-loan"] },
  { slug: "pmi", term: "PMI (Private Mortgage Insurance)", category: "Mortgages", shortDef: "Insurance required by lenders when a borrower's down payment is less than 20% of the home's purchase price.", fullDef: "Private Mortgage Insurance (PMI) is a type of insurance that protects the lender — not the borrower — if you default on your mortgage. It is typically required when your down payment is less than 20% of the home's purchase price (LTV above 80%). PMI typically costs 0.5–1.5% of the original loan amount per year, added to your monthly payment. Once you reach 20% equity, you can request PMI cancellation; lenders must automatically cancel it at 22% equity.", example: "On a $350,000 loan with 0.8% PMI, you'd pay $2,800/year ($233/month) in PMI until you reach 20% equity. This is a significant cost that makes a larger down payment financially attractive.", related: ["loan-to-value", "down-payment", "mortgage"] },
  { slug: "points", term: "Mortgage Points (Discount Points)", category: "Mortgages", shortDef: "Upfront fees paid to a lender to reduce the interest rate on a mortgage. One point equals 1% of the loan amount.", fullDef: "Mortgage discount points are prepaid interest paid at closing to permanently reduce your mortgage interest rate. One point equals 1% of the loan amount and typically reduces the rate by 0.25%. Paying points makes sense if you plan to stay in the home long enough to recoup the upfront cost through lower monthly payments — this is called the break-even point.", example: "On a $400,000 mortgage, one point costs $4,000 and might reduce your rate from 7.0% to 6.75%. The lower rate saves ~$65/month. Break-even: $4,000 / $65 = ~61 months (5 years).", related: ["apr", "origination-fee", "refinance"] },
  { slug: "principal", term: "Principal", category: "Loans & Credit", shortDef: "The original amount of money borrowed, not including interest.", fullDef: "Principal refers to the original sum of money borrowed in a loan, or the remaining balance that has not yet been repaid. When you make loan payments, a portion goes toward interest and a portion reduces the principal. In the early stages of an amortizing loan, most of the payment covers interest. As the principal decreases over time, more of each payment goes toward reducing the balance.", example: "If you borrow $200,000 for a mortgage, your principal is $200,000. After 5 years of payments, your principal balance might be $185,000 — meaning you've paid down $15,000 of the original loan.", related: ["amortization", "interest-rate", "loan-term"] },
  { slug: "refinance", term: "Refinance", category: "Mortgages", shortDef: "Replacing an existing loan with a new one, typically to get a lower interest rate or change the loan terms.", fullDef: "Refinancing means paying off an existing loan by taking out a new loan, usually with different terms. Homeowners refinance to secure a lower interest rate, reduce their monthly payment, shorten their loan term, switch from an adjustable to a fixed rate, or access home equity (cash-out refinance). Refinancing involves closing costs (typically 2–5% of the loan amount), so it's important to calculate the break-even point to ensure it makes financial sense.", example: "Refinancing a $300,000 mortgage from 8% to 6.5% saves ~$280/month. With $6,000 in closing costs, the break-even point is about 21 months. If you plan to stay longer, refinancing makes sense.", related: ["mortgage", "closing-costs", "equity"] },
  { slug: "revolving-credit", term: "Revolving Credit", category: "Credit Cards", shortDef: "A type of credit that allows you to borrow, repay, and borrow again up to a set credit limit.", fullDef: "Revolving credit is a type of credit account where you have a set credit limit and can borrow any amount up to that limit, repay it, and borrow again repeatedly. Credit cards and home equity lines of credit (HELOCs) are the most common forms of revolving credit. Unlike installment loans (which have fixed payments and a set end date), revolving credit is ongoing and flexible. Your credit utilization ratio — a key credit score factor — is based entirely on revolving credit accounts.", example: "A credit card with a $10,000 limit is revolving credit. You charge $3,000, pay it off, charge $5,000, pay $2,000, and carry $3,000 — all within your limit. Your utilization fluctuates accordingly.", related: ["credit-utilization", "credit-limit", "installment-loan"] },
  { slug: "savings-account", term: "Savings Account", category: "Savings & Investing", shortDef: "A basic deposit account at a bank or credit union that earns interest on your balance.", fullDef: "A savings account is a deposit account held at a bank or credit union that earns interest on your balance. Traditional savings accounts at large banks often pay very low interest rates (0.01–0.5% APY). High-yield savings accounts (HYSAs) at online banks typically pay significantly more (4–5%+ APY). Savings accounts are FDIC-insured up to $250,000 and are designed for money you want to keep safe and accessible.", example: "Keeping $10,000 in a traditional savings account at 0.1% APY earns $10/year. Moving it to a high-yield savings account at 4.5% APY earns $450/year — a $440 difference for doing nothing.", related: ["apy", "fdic-insurance", "money-market"] },
  { slug: "secured-loan", term: "Secured Loan", category: "Loans & Credit", shortDef: "A loan backed by collateral — an asset the lender can seize if you default.", fullDef: "A secured loan is backed by collateral — an asset that the lender can claim if you fail to repay the loan. Mortgages (secured by the home) and auto loans (secured by the vehicle) are the most common examples. Because the lender has less risk, secured loans typically offer lower interest rates than unsecured loans. If you default, the lender can foreclose on your home or repossess your car.", example: "An auto loan is a secured loan. If you stop making payments, the lender can repossess your car. This lower risk for the lender is why auto loan rates are typically lower than personal loan rates.", related: ["unsecured-loan", "collateral", "default"] },
  { slug: "soft-inquiry", term: "Soft Inquiry", category: "Credit Score", shortDef: "A credit check that does not affect your credit score, such as a background check or pre-approval check.", fullDef: "A soft inquiry (or soft pull) is a credit check that does not affect your credit score. Soft inquiries occur when you check your own credit, when a company checks your credit for pre-approval offers, or when an employer runs a background check. Unlike hard inquiries, soft inquiries are not visible to other lenders and do not impact your creditworthiness. Many lenders now offer pre-qualification tools that use only soft inquiries.", example: "Checking your own credit score on Credit Karma, receiving a pre-approved credit card offer in the mail, or an employer running a background check — all are soft inquiries that don't affect your score.", related: ["hard-inquiry", "credit-score", "credit-report"] },
  { slug: "unsecured-loan", term: "Unsecured Loan", category: "Loans & Credit", shortDef: "A loan not backed by collateral, approved based on your creditworthiness alone.", fullDef: "An unsecured loan is a loan that is not backed by any collateral. Approval is based solely on your creditworthiness — your credit score, income, and debt-to-income ratio. Because the lender has no asset to seize if you default, unsecured loans carry more risk for the lender and typically come with higher interest rates than secured loans. Credit cards and personal loans are the most common forms of unsecured credit.", example: "A personal loan for debt consolidation is typically unsecured. If you default, the lender can't repossess anything — but they can sue you, damage your credit, and send the debt to collections.", related: ["secured-loan", "personal-loan", "credit-score"] },
  { slug: "variable-rate", term: "Variable Rate (Adjustable Rate)", category: "Loans & Credit", shortDef: "An interest rate that can change over time based on a benchmark rate, such as the prime rate.", fullDef: "A variable interest rate (also called an adjustable rate) fluctuates over time based on changes in a benchmark interest rate, such as the prime rate or SOFR (Secured Overnight Financing Rate). Variable rates often start lower than fixed rates, making them attractive initially. However, they carry the risk of increasing over time. Most adjustable-rate mortgages (ARMs) have an initial fixed period (e.g., 5 years) before the rate begins adjusting.", example: "A 5/1 ARM mortgage has a fixed rate for the first 5 years, then adjusts annually. If rates rise significantly during the adjustable period, your monthly payment could increase by hundreds of dollars.", related: ["fixed-rate", "interest-rate", "adjustable-rate-mortgage"] },
];

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

// ─── Glossary Index Page ──────────────────────────────────────────────────────

export function GlossaryIndexPage() {
  const [search, setSearch] = useState("");
  const [activeLetter, setActiveLetter] = useState<string | null>(null);

  const filtered = useMemo(() => {
    let terms = GLOSSARY_TERMS;
    if (search.trim()) {
      const q = search.toLowerCase();
      terms = terms.filter((t) => t.term.toLowerCase().includes(q) || t.shortDef.toLowerCase().includes(q));
    }
    if (activeLetter && !search.trim()) {
      terms = terms.filter((t) => t.term.toUpperCase().startsWith(activeLetter));
    }
    return terms.sort((a, b) => a.term.localeCompare(b.term));
  }, [search, activeLetter]);

  const byLetter = useMemo(() => {
    const map: Record<string, typeof GLOSSARY_TERMS> = {};
    filtered.forEach((t) => {
      const l = t.term[0].toUpperCase();
      if (!map[l]) map[l] = [];
      map[l].push(t);
    });
    return map;
  }, [filtered]);

  const availableLetters = new Set(GLOSSARY_TERMS.map((t) => t.term[0].toUpperCase()));

  return (
    <PublicLayout>
      <SEOMeta
        title="Financial Terms Glossary — Definitions & Explanations"
        description="Plain-English definitions for over 40 financial terms — APR, APY, credit score, amortization, HELOC, PMI, and more. Free from First Capital Alliance."
        keywords="financial glossary, financial terms, APR definition, credit score definition, mortgage terms, banking terms"
        canonical="/glossary"
      />
      <div className="bg-[var(--navy-900)] text-white py-14">
        <div className="container">
          <Breadcrumb items={[{ label: "Financial Glossary" }]} />
          <h1 className="text-4xl md:text-5xl font-bold mt-4 mb-4 font-serif">Financial Terms Glossary</h1>
          <p className="text-lg text-white/75 max-w-2xl mb-6">Plain-English definitions for the financial terms that matter most — no jargon, no confusion.</p>
          <div className="relative max-w-lg">
            <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-white/50" />
            <input
              type="text"
              placeholder="Search terms..."
              value={search}
              onChange={(e) => { setSearch(e.target.value); setActiveLetter(null); }}
              className="w-full bg-white/10 border border-white/20 rounded-xl pl-10 pr-4 py-3 text-white placeholder:text-white/50 focus:outline-none focus:ring-2 focus:ring-accent/60 text-sm"
            />
          </div>
        </div>
      </div>

      <div className="container py-10">
        {/* Alphabet filter */}
        {!search && (
          <div className="flex flex-wrap gap-1.5 mb-8">
            <button
              onClick={() => setActiveLetter(null)}
              className={`px-3 py-1.5 rounded-lg text-sm font-medium transition-colors ${activeLetter === null ? "bg-accent text-white" : "bg-muted text-muted-foreground hover:bg-muted/80"}`}
            >All</button>
            {ALPHABET.map((l) => (
              <button
                key={l}
                onClick={() => setActiveLetter(activeLetter === l ? null : l)}
                disabled={!availableLetters.has(l)}
                className={`w-9 h-9 rounded-lg text-sm font-mono font-semibold transition-colors ${activeLetter === l ? "bg-accent text-white" : availableLetters.has(l) ? "bg-muted text-foreground hover:bg-muted/80" : "bg-muted/30 text-muted-foreground/30 cursor-not-allowed"}`}
              >{l}</button>
            ))}
          </div>
        )}

        {filtered.length === 0 ? (
          <div className="text-center py-16 text-muted-foreground">No terms found for "{search}".</div>
        ) : search ? (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filtered.map((t) => (
              <TermCard key={t.slug} term={t} />
            ))}
          </div>
        ) : (
          <div className="space-y-10">
            {Object.entries(byLetter).sort(([a], [b]) => a.localeCompare(b)).map(([letter, terms]) => (
              <div key={letter} id={`letter-${letter}`}>
                <h2 className="text-2xl font-bold font-serif text-foreground mb-4 border-b border-border pb-2">{letter}</h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                  {terms.map((t) => <TermCard key={t.slug} term={t} />)}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </PublicLayout>
  );
}

function TermCard({ term }: { term: typeof GLOSSARY_TERMS[0] }) {
  return (
    <Link href={`/glossary/${term.slug}`} className="group block bg-card border border-border rounded-xl p-5 hover:border-accent hover:shadow-md transition-all">
      <div className="flex items-start justify-between gap-2 mb-2">
        <h3 className="font-semibold text-foreground group-hover:text-accent transition-colors text-sm leading-snug">{term.term}</h3>
        <ChevronRight className="w-4 h-4 text-muted-foreground shrink-0 mt-0.5 group-hover:text-accent transition-colors" />
      </div>
      <span className="text-xs text-muted-foreground bg-muted px-2 py-0.5 rounded-full mb-2 inline-block">{term.category}</span>
      <p className="text-xs text-muted-foreground leading-relaxed line-clamp-2">{term.shortDef}</p>
    </Link>
  );
}

// ─── Individual Term Page ─────────────────────────────────────────────────────

export function GlossaryTermPage() {
  const params = useParams<{ slug: string }>();
  const slug = params.slug;
  const term = GLOSSARY_TERMS.find((t) => t.slug === slug);

  if (!term) {
    return (
      <PublicLayout>
        <div className="container py-20 text-center">
          <h1 className="text-3xl font-bold mb-4">Term Not Found</h1>
          <Link href="/glossary" className="text-accent hover:underline">← Back to Glossary</Link>
        </div>
      </PublicLayout>
    );
  }

  const relatedTerms = term.related?.map((slug) => GLOSSARY_TERMS.find((t) => t.slug === slug)).filter(Boolean) ?? [];

  return (
    <PublicLayout>
      <SEOMeta
        title={`${term.term} — Definition & Explanation`}
        description={term.shortDef}
        canonical={`/glossary/${term.slug}`}
      />
      <div className="bg-[var(--navy-900)] text-white py-12">
        <div className="container">
          <Breadcrumb items={[{ label: "Glossary", href: "/glossary" }, { label: term.term }]} />
          <span className="text-xs text-white/60 bg-white/10 px-3 py-1 rounded-full mt-4 inline-block">{term.category}</span>
          <h1 className="text-4xl font-bold mt-3 mb-3 font-serif">{term.term}</h1>
          <p className="text-lg text-white/75 max-w-2xl">{term.shortDef}</p>
        </div>
      </div>

      <div className="container py-12">
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="lg:col-span-2 space-y-8">
            <div className="bg-card border border-border rounded-xl p-6">
              <h2 className="text-xl font-bold font-serif mb-4 text-foreground">Full Definition</h2>
              <p className="text-foreground leading-relaxed">{term.fullDef}</p>
            </div>
            {term.example && (
              <div className="bg-accent/5 border border-accent/20 rounded-xl p-6">
                <h2 className="text-lg font-bold font-serif mb-3 text-foreground flex items-center gap-2">
                  <span className="w-6 h-6 bg-accent text-white rounded-full text-xs flex items-center justify-center font-bold">E</span>
                  Example
                </h2>
                <p className="text-foreground leading-relaxed">{term.example}</p>
              </div>
            )}
          </div>

          <div className="space-y-5">
            {relatedTerms.length > 0 && (
              <div className="bg-card border border-border rounded-xl p-5">
                <h3 className="font-semibold text-foreground mb-3 text-sm uppercase tracking-wider">Related Terms</h3>
                <div className="space-y-2">
                  {relatedTerms.map((rt) => rt && (
                    <Link key={rt.slug} href={`/glossary/${rt.slug}`} className="flex items-center justify-between group py-2 border-b border-border last:border-0">
                      <span className="text-sm text-foreground group-hover:text-accent transition-colors">{rt.term}</span>
                      <ChevronRight className="w-3.5 h-3.5 text-muted-foreground group-hover:text-accent transition-colors" />
                    </Link>
                  ))}
                </div>
              </div>
            )}
            <div className="bg-[var(--navy-900)] text-white rounded-xl p-5">
              <h3 className="font-semibold mb-2">Browse All Terms</h3>
              <p className="text-white/70 text-sm mb-4">Explore our complete financial glossary.</p>
              <Link href="/glossary" className="text-accent text-sm font-medium hover:underline">View Full Glossary →</Link>
            </div>
          </div>
        </div>
      </div>
    </PublicLayout>
  );
}
